# Change default server ports
server:
  applicationConnectors:
  - type: http
    port: 8090
  adminConnectors:
  - type: http
    port: 8091

mongo:
  seeds:
  - host: localhost
    port: 27017
  database: piData
#   credentials:
#    userName: superuser
#    password: 12345678

